import type { Metadata } from "next";
import "./globals.css";
import { ErrorBoundary } from "@/components/ErrorBoundary";
import StorageBridge from "@/app/_bridges/StorageBridge";
import InputBehaviorBridge from "@/app/_bridges/InputBehaviorBridge";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={`antialiased`}>
        <StorageBridge />
        <InputBehaviorBridge />
        <ErrorBoundary>{children}</ErrorBoundary>
      </body>
    </html>
  );
}
